name: your mom
on: [push]
env:
  TYPE: build
  TZ: America/Recife

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@master

       - name: kek
         run: |
              aria2c https://mor1.uploads.androidfilehost.com/dl/JAY0YO38KQoyVwJIjHGchQ/1605211550/10763459528675581974/1GTyE6iW0H6zrfQTxJms6AwZY_1rWqHzF
              mv 1GTyE6iW0H6zrfQTxJms6AwZY_1rWqHzF cock.zip
              ls
              sudo unzip cock.zip
              ls
              sudo unzip *.lz4
              ls
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet *vendor*

